sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - "node"
  - "12"
  - "10"
  - "9"
  - "8"

install:
  # the prepare script run during install currently does clean-build
  - npm install

script:
  - npm test
  - npm run test-spec
  - node ./bin.js trace test
  - node ./bin.js "**/{*.ts,*.md}"


jobs:
  include:
    - stage: "Coverage"
      script:
        - npm run travis-coverage
