name: Create Version Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version Bump"
        type: choice
        options:
          - "alpha"
          - "patch"
          - "minor"
          - "auto"
        default: "auto"
        required: true
      dry_run:
        description: "Dry Run"
        type: choice
        options:
          - "yes"
          - "no"
        default: "yes"
        required: false

  workflow_call:
    secrets:
      PUBLISH_NPM:
        required: true

permissions:
  contents: write

env:
  USE_NEXT: ${{ inputs.bump == 'alpha' }}
  BUMP: ${{ (inputs.bump != 'auto' && inputs.bump != 'alpha' && inputs.bump) || '' }}
  DRY_RUN: ${{ (inputs.dry_run == 'yes' && '--git-dry-run') || '' }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: Version
        run: |
          echo "VERSION=$(jq .version lerna.json)" >> $GITHUB_ENV

      - name: Mode
        env:
          MODE: >
            ${{ (env.USE_NEXT && '--conventional-prerelease')
            || (contains(env.VERSION, 'alpha') && '--conventional-graduate')
            || ''
            }}
        run: |
          echo MODE=$MODE >> $GITHUB_ENV

      - name: Install
        run: pnpm i

      - name: Push Version
        run: pnpm lerna version --conventional-commits --sync-workspace-lock --yes ${{ env.MODE }} ${{ env.DRY_RUN }} ${{ env.BUMP }}
