name: Create Version Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version Bump"
        type: choice
        options:
          - "alpha"
          - "patch"
          - "minor"
          - "auto"
        default: "alpha"
        required: true
      dry_run:
        description: "Dry Run"
        type: choice
        options:
          - "yes"
          - "no"
        default: "yes"
        required: false

  workflow_call:
    secrets:
      token:
        required: true

permissions:
  contents: write

env:
  USE_NEXT: ${{ inputs.bump == 'alpha' }}
  BUMP: ${{ (inputs.bump != 'auto' && inputs.bump != 'alpha' && inputs.bump) || '' }}
  DRY_RUN: ${{ (inputs.dry_run == 'yes' && '--git-dry-run') || '' }}

jobs:
  release_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: pnpm

      - name: Version
        run: |
          echo "VERSION=$(jq -r .version lerna.json)" >> $GITHUB_ENV

      - name: Mode
        env:
          MODE: >
            ${{ (env.USE_NEXT == 'true' && '--conventional-prerelease')
            || (contains(env.VERSION, 'alpha') && '--conventional-graduate')
            || ''
            }}
        run: |
          echo MODE=$MODE >> $GITHUB_ENV

      - uses: tibdex/github-app-token@7ce9ffdcdeb2ba82b01b51d6584a6a85872336d4 # v1.5 # cspell:ignore tibdex
        if: ${{ !env.DRY_RUN && !inputs.token }}
        id: generate-token
        with:
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}

      - name: Setup Git
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}
        run: |
          git config user.name streetsidesoftware[bot]
          git config user.email streetsidesoftware[bot]@users.noreply.github.com
          git remote add gh-token "https://$GH_TOKEN@github.com/streetsidesoftware/cspell.git"

      - name: Install
        run: pnpm i

      - name: Push Version
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}
        run: pnpm lerna version --conventional-commits --sync-workspace-lock --yes ${{ env.MODE }} ${{ env.DRY_RUN }} ${{ env.BUMP }} --no-push

      - name: Trigger Workflows
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token || secrets.GITHUB_TOKEN }}
        run: |
          git commit --allow-empty -m "chore: release $(jq -r .version lerna.json)" -m "Mark Release $(jq -r .version lerna.json)"
          git push origin main --follow-tags
