name: Build and Cache Dist

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

permissions:
  contents: read

env:
  REF_BRANCH: main
  RUNS_ON: ubuntu-latest
  NODE_VERSION: "16.x"
  NPM_VERSION: "8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            packages/*/package-lock.json
            integration-tests/package-lock.json

      - run: npm i -g npm@${{ env.NPM_VERSION }}
      - run: npm -v

      - name: Cache Build
        id: step-cache-build
        uses: actions/cache@v3
        with:
          key: |
            int-build-${{ hashFiles(
              'integration-tests/package-lock.json', 'integration-tests/src/**/*.ts', 'integration-tests/tsconfig.json',
              'packages/*/package-lock.json', 'packages/*/src/**/*.ts', 'packages/*/tsconfig.json'
            ) }}
          path: |
            packages/*/dist
            integration-tests/dist

      - name: Cached Results
        run: |
          echo Build Cache: ${{ steps.step-cache-build.outputs.cache-hit && 'Hit' || 'Miss' }}

      - name: Npm CI
        if: ${{ !steps.step-cache-build.outputs.cache-hit }}
        run: npm ci

      - name: Has Npm has failed?
        if: ${{ failure() }}
        run: |
          ls -alF /home/runner/.npm/_logs/*.log
          cat /home/runner/.npm/_logs/*.log

      - name: Build
        if: ${{ !steps.step-cache-build.outputs.cache-hit }}
        run: npm run build
