name: Lint
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "website/**"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "website/**"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup and Build
        uses: ./.github/actions/install-build
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint
        run: pnpm run lint

      - name: PR Auto Fix Lint
        env:
          EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$EVENT"
