name: Publish

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        description: 'Branch to run on "master" or "cspell4"'
        # Default value if no value is explicitly provided
        default: master
        # Input has to be provided for the workflow to run
        required: true

jobs:
  publish-manual:
    runs-on: ubuntu-latest
    if: github.event.inputs.branch == 'master' || github.event.inputs.branch == 'cspell4'
    steps:
      - name: Echo context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 10
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      - name: Setup Git
        run: |
          git config --global user.name 'Jason Dent'
          git config --global user.email 'jason@streetsidesoftware.nl'
      - name: Publish Master
        if: ${{ github.event.inputs.branch == 'master' }}
        run: npm run pub-lerna -- -y --dist-tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish cspell4
        if: ${{ github.event.inputs.branch == 'cspell4' }}
        run: npm run pub-lerna -- -y --dist-tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-tag:
    runs-on: ubuntu-latest
    if: ${{ !github.event.inputs.branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Test
        run: npm test
      - name: Echo context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Setup Git
        run: |
          git config --global user.name 'Jason Dent'
          git config --global user.email 'jason@streetsidesoftware.nl'
#       - name: Publish Master
#         if: ${{ github.ref == 'refs/heads/master' }}
#         run: npm run pub-lerna -- -y --dist-tag next
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Publish cspell4
#         if: ${{ github.ref == 'refs/heads/cspell4' }}
#         run: npm run pub-lerna -- -y --dist-tag latest
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
